### ISSUE TITLE
Version 1.1 Banners Update

### ISSUE THREAD

**Issue by uzair-ashraf** [uzair-ashraf/genshin-impact-wish-simulator#24]
# Version 1.1 Banners Update

## Plan
Genshin Impact has released a new update for v1.1, which is one new banner, and updating the two existing banners.  Will require the following updates:

## Task List
- [x] Create asset for _Farewell of Snezhnaya_ Banner
- [x] Create asset for new _Epitome Invocation_ Banner
- [x] Create asset for new _Wanderlust Invocation_ Banner
- [x] Create details page for _Farewell of Snezhnaya_ Banner
- [x] Create JSON file for characters and items of _Farewell of Snezhnaya_ Banner
- [x] Update JSON file for new _Epitome Invocation_ Banner
- [x] Update JSON file for new _Wanderlust Invocation_ Banner
- [x] Obtain assets for the following new characters and items
     -  Tartaglia
     -  Diona
     -  Memory of Dust
- [x] Update details page for new _Epitome Invocation_ Banner
- [x] Update details page for new _Wanderlust Invocation_ Banner
- [x] Create class for _Farewell of Snezhnaya_ Banner
- [x] Update class for new _Epitome Invocation_ Banner
- [x] Update class for new _Wanderlust Invocation_ Banner
- [x] Add  _Farewell of Snezhnaya_ Banner to test suite
- [x] Update  _Epitome Invocation_ Banner in test suite
- [x] Update new _Wanderlust Invocation_ Banner in test suite
- [x] Test for bugs
- [x] Update version in package.json
