### ISSUE TITLE
User can wish once

### ISSUE THREAD

**Issue by NatKeely** [uzair-ashraf/genshin-impact-wish-simulator#29]
As in the real game, a single pull option would be really greate for those who wants to pull this way.

Maybe next feature to add ?

**Comment by uzair-ashraf** [comment]
This will require quite a big refactor to UI and all tests, but this will be the next feature added.

**Comment by uzair-ashraf** [comment]
## Intention
Users want to be able to roll for one pull.  This will require a refactor to the UI's system on resetting the user's history, but also leaves an opening to add a settings system.

## Task List
- [ ] Refactor Base Gacha abstract class to have a single pull method, to retrieve one drop based off the class's probability range
- [ ] Refactor UI to replace Reset button with `Wish` button.
- [ ] Replace close button on banners page to pop a settings modal, where user's can there reset their inventory, along with any new additions to the system can be added there as well.
- [ ] Incorporate the settings button to mobile view
- [ ] Refactor Beginner's wish hiding system to disable the 10 wish system if the attempts go over 10 instead of being divisble by 20
- [ ] Collect assets for a single item wish with a new type of animation
- [ ] Create a new wish-results component to handle single wishes
- [ ] Discuss new UI for a single item drop
- [ ] Update unit tests to incorporate single pull
- [ ] Update integration tests to incorporate single pull
- [ ] Deploy to staging to ensure stable build for all platforms
