### ISSUE TITLE
Gentry of Hermitage Update

### ISSUE THREAD

**Issue by uzair-ashraf** [uzair-ashraf/genshin-impact-wish-simulator#32]
# Gentry of Hermitage Update

## Plan
Genshin Impact has released a new banner and an update to Epitome Invocation

## Task List
- [x] Create asset for _Gentry of Hermitage_ Banner
- [x] Create asset for new _Epitome Invocation_ Banner
- [x] Create details page for _Gentry of Hermitage_ Banner
- [x] Create JSON file for characters and items of _Gentry of Hermitage_ Banner
- [x] Update JSON file for new _Epitome Invocation_ Banner
- [x] Obtain assets for the following new characters and items
     - [x]  Zhongli
     - [x] Xinyan 
     - [x] Vortex Vanquisher
     - [x] The Unforged
- [x] Update details page for new _Epitome Invocation_ Banner
- [x] Create class for _Gentry of Hermitage_ Banner
- [x] Update class for new _Epitome Invocation_ Banner
- [x] Add  _Gentry of Hermitage_ Banner to test suite
- [x] Test for bugs
- [x] Update version in package.json
