### ISSUE TITLE
Version 1.2 Update

### ISSUE THREAD

**Issue by uzair-ashraf** [uzair-ashraf/genshin-impact-wish-simulator#43]
# Version 1.2 Update

## Plan
Genshin Impact has released a new banner and an update to Epitome Invocation

## Task List
- [x] Create asset for _Secretum Secretorum_ Banner
- [x] Create asset for new _Epitome Invocation_ Banner
- [x] Create details page for _Secretum Secretorum_ Banner
- [x] Create JSON file for characters and items of _Secretum Secretorum_ Banner
- [x] Update JSON file for new _Epitome Invocation_ Banner
- [x] Update JSON file for new _Wanderlust Invocation_ Banner
- [x] Obtain assets for the following new characters and items
    - [x] Albedo
    - [x] Summit Shaper
- [x] Update details page for new _Epitome Invocation_ Banner
- [x] Update details page for new _Wanderlust Invocation_ Banner
- [x] Create class for _Secretum Secretorum_ Banner
- [x] Update class for new _Epitome Invocation_ Banner
- [x] Add  _Secretum Secretorum_ Banner to test suite
- [x] Test for bugs
- [x] Update version in package.json
