### ISSUE TITLE
Version 1.2.1 Update

### ISSUE THREAD

**Issue by uzair-ashraf** [uzair-ashraf/genshin-impact-wish-simulator#48]
# Version 1.2.1 Update

## Plan
Genshin Impact has released a new banner and an update to Epitome Invocation

## Task List
- [x] Create asset for _Adrift in the Harbor_ Banner
- [x] Create asset for new _Epitome Invocation_ Banner
- [x] Create details page for _Adrift in the Harbor_ Banner
- [x] Create JSON file for characters and items of _Adrift in the Harbor_ Banner
- [x] Update JSON file for new _Epitome Invocation_ Banner
- [x] Update JSON file for new _Wanderlust Invocation_ Banner
- [x] Obtain assets for the following new characters and items
    - [x] Ganyu
- [x] Update details page for new _Epitome Invocation_ Banner
- [x] Create class for _Adrift in the Harbor_ Banner
- [x] Update class for new _Epitome Invocation_ Banner
- [x] Add  _Adrift in the Harbor_ Banner to test suite
- [x] Test for bugs
- [x] Update version in package.json
