### ISSUE TITLE
Version 1.3 Update

### ISSUE THREAD

**Issue by uzair-ashraf** [uzair-ashraf/genshin-impact-wish-simulator#60]
# Version 1.3.0 Update

## Plan
Genshin Impact has released a new banner

## Task List
- [x] Create asset for _Invitation To Mundane Life_ Banner
- [x] Create asset for new _Epitome Invocation_ Banner
- [x] Create details page for _Invitation To Mundane Life_ Banner
- [x] Create JSON file for characters and items of _Invitation To Mundane Life_ Banner
- [x] Update JSON file for new _Epitome Invocation_ Banner
- [x] Update JSON file for new _Wanderlust Invocation_ Banner
- [x] Obtain assets for the following new characters and items
    - [x] Xiao
- [x] Update details page for new _Epitome Invocation_ Banner
- [x] Create class for _Invitation To Mundane Life_ Banner
- [x] Update class for new _Epitome Invocation_ Banner
- [x] Add  _Invitation To Mundane Life_ Banner to test suite
- [x] Test for bugs
- [x] Update version in package.json
- [x] Test deployment to staging
