### ISSUE TITLE
Version 1.4 Update

### ISSUE THREAD

**Issue by uzair-ashraf** [uzair-ashraf/genshin-impact-wish-simulator#75]
# Version 1.4 Update

## Plan
Genshin Impact has released a new banner

## Task List
- [x] Create asset for _Ballad Of Goblets_ Banner
- [x] Create asset for new _Epitome Invocation_ Banner
- [x] Create details page for __Ballad Of Goblets_ Banner
- [x] Create JSON file for characters and items of __Ballad Of Goblets_ Banner
- [x] Update JSON file for new _Epitome Invocation_ Banner
- [x] Obtain assets for the following new characters and items
    - [x] Elegy for the end
    - [x] The alley of the flash 
- [x] Update details page for new _Epitome Invocation_ Banner
- [x] Create class for _Ballad Of Goblets_ Banner
- [x] Update class for new _Epitome Invocation_ Banner
- [x] Test for bugs
- [x] Update version in package.json
- [x] Test deployment to staging
